language: csharp
mono: none
dotnet: 3.1
sudo: false
cache:
  directories:
  - "$HOME/.nuget/"
before_install:
- set -e
addons:
  apt:
    packages:
    # This package is used only to address an issue in Travis CI, which would
    # otherwise install a newer 2.1.x preview which breaks the build.
script:
- bash ./$CODEBASE/scripts/build
