# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
